"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Bell, Bookmark, CalendarDays, Cat, Check, ChevronDown, ChevronRight, Heart, Home, LogOut, MapPin, Menu, MessageCircle, Pencil, Plus, Search, ShieldCheck, SlidersHorizontal, Sparkles, Star, Trash2, X } from "lucide-react";
import { places, reviews, type Place } from "@/lib/data";
import { AuthModal, Onboarding, type DemoUser } from "@/components/functional-modals";
import { defaultCat, usePersistentState, type CatProfile, type Reminder, type UserReview } from "@/lib/use-persistent-state";
import { validateCommunityContent } from "@/lib/content-filter";
import { createClient } from "@/lib/supabase";
import { loadPrivateData, saveCat as saveCatRemote, saveReminder as saveReminderRemote } from "@/lib/supabase-repository";

type Tab = "Inicio" | "Explorar" | "Mi gato" | "Agenda";
type Editor = "cat" | "reminder" | "review" | "compare" | null;

function Logo(){return <div className="logo"><span className="logo-mark"><Cat size={20}/></span><span>Miau<span>pedia</span></span></div>}
function Stars({rating}:{rating:number}){return <span className="stars"><Star size={15} fill="currentColor"/><b>{rating.toFixed(1)}</b></span>}
function Disclaimer(){return <div className="disclaimer"><ShieldCheck/><p><b>Información comunitaria, no asesoramiento médico.</b><br/>Miaupedia no reemplaza la atención veterinaria ni proporciona diagnósticos, tratamientos o recomendaciones médicas.</p></div>}
function LockedState({onLogin}:{onLogin:()=>void}){return <div className="empty locked"><ShieldCheck/><h3>Tu espacio personal está protegido</h3><p>Inicia sesión para guardar y sincronizar esta información.</p><button onClick={onLogin}>Iniciar sesión</button></div>}
function catCompletion(cat:CatProfile){return Math.round(([cat.name,cat.age,cat.sex,cat.breed,cat.birthDate,cat.weight,cat.photo,cat.food.length+cat.litter.length+cat.toys.length].filter(Boolean).length/8)*100)}

function PlaceCard({place,saved,onSave,onOpen,onCompare}:{place:Place;saved:boolean;onSave:()=>void;onOpen:()=>void;onCompare:()=>void}){
  return <article className="place-card" onClick={onOpen}><div className="place-image" style={{backgroundImage:`url(${place.image})`}}>{place.sponsored&&<span className="sponsored">Patrocinado</span>}<button className={`save ${saved?"active":""}`} onClick={e=>{e.stopPropagation();onSave()}} aria-label="Guardar"><Heart size={18} fill={saved?"currentColor":"none"}/></button></div><div className="place-copy"><div className="place-meta"><span>{place.category}</span><Stars rating={place.rating}/></div><h3>{place.name}</h3><p><MapPin size={14}/> {place.district} · {place.reviews} reseñas</p><div className="tags">{place.tags.map(t=><span key={t}>{t}</span>)}</div><div className="price-row"><strong>{place.price}</strong>{place.category==="Producto"?<button className="compare-add" onClick={e=>{e.stopPropagation();onCompare()}}>Comparar</button>:place.open&&<span className="open">Abierto ahora</span>}</div></div></article>
}

export function MiaupediaApp(){
  const [tab,setTab]=useState<Tab>("Inicio"); const [query,setQuery]=useState(""); const [category,setCategory]=useState("Todos"); const [district,setDistrict]=useState("Todos");
  const [saved,setSaved]=usePersistentState<number[]>("miaupedia:follows",[1]); const [cats,setCats,hydrated]=usePersistentState<CatProfile[]>("miaupedia:cats",[defaultCat]);
  const [reminders,setReminders]=usePersistentState<Reminder[]>("miaupedia:reminders",[{id:"r1",catId:"demo-luna",type:"Desparasitación",date:"2026-06-24",description:"Desparasitación programada",completed:false},{id:"r2",catId:"demo-luna",type:"Vacuna",date:"2026-08-12",description:"Vacuna anual",completed:false}]);
  const [userReviews,setUserReviews]=usePersistentState<UserReview[]>("miaupedia:reviews",[]); const [user,setUser]=usePersistentState<DemoUser|null>("miaupedia:user",null); const [onboarded,setOnboarded]=usePersistentState("miaupedia:onboarded",false);
  const [selected,setSelected]=useState<Place|null>(null); const [compare,setCompare]=useState<number[]>([]); const [showFilters,setShowFilters]=useState(false); const [notice,setNotice]=useState("");
  const [authOpen,setAuthOpen]=useState(false); const [showOnboarding,setShowOnboarding]=useState(false); const [editor,setEditor]=useState<Editor>(null); const [editingCat,setEditingCat]=useState<CatProfile|null>(null); const [editingReview,setEditingReview]=useState<UserReview|null>(null); const [mobileOpen,setMobileOpen]=useState(false);
  const primaryCat=cats[0]; const flash=(m:string)=>{setNotice(m);setTimeout(()=>setNotice(""),2500)}; const requireUser=(fn:()=>void)=>user?fn():setAuthOpen(true);
  const results=useMemo(()=>places.filter(p=>(category==="Todos"||p.category===category)&&(district==="Todos"||p.district===district)&&`${p.name} ${p.category} ${p.district}`.toLowerCase().includes(query.toLowerCase())),[category,district,query]);
  useEffect(()=>{const s=createClient();if(!s)return;const apply=async(id:string)=>{try{const remote=await loadPrivateData(id);if(remote){setCats(remote.cats);setReminders(remote.reminders);setUserReviews(remote.userReviews)}}catch{flash("Sesión iniciada; no se pudo sincronizar la base de datos")}};s.auth.getUser().then(({data})=>{if(data.user){setUser({id:data.user.id,email:data.user.email||"",name:data.user.user_metadata.display_name||"Miauamigo"});void apply(data.user.id)}});const {data:l}=s.auth.onAuthStateChange((_e,session)=>{if(session){setUser({id:session.user.id,email:session.user.email||"",name:session.user.user_metadata.display_name||"Miauamigo"});void apply(session.user.id)}});return()=>l.subscription.unsubscribe()},[setCats,setReminders,setUser,setUserReviews]);
  const navigate=(next:Tab)=>{setTab(next);setMobileOpen(false);window.scrollTo({top:0,behavior:"smooth"})};
  const toggleSaved=(id:number)=>requireUser(()=>{setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);flash(saved.includes(id)?"Eliminado de favoritos":"Guardado en Favoritos")});
  const addCompare=(id:number)=>{setCompare(v=>v.includes(id)?v.filter(x=>x!==id):v.length<3?[...v,id]:v); if(compare.length>=3&&!compare.includes(id))flash("Puedes comparar hasta 3 productos")};
  const signOut=async()=>{await createClient()?.auth.signOut();setUser(null);flash("Sesión cerrada")};
  useEffect(()=>{if(!user||!createClient())return;cats.filter(c=>c.id!=="demo-luna").forEach(c=>void saveCatRemote(user.id,c).catch(()=>undefined));reminders.filter(r=>r.catId!=="demo-luna").forEach(r=>void saveReminderRemote(r).catch(()=>undefined))},[cats,reminders,user]);
  if(!hydrated)return <div className="app-loading"><Logo/><span/></div>;

  return <div className="app-shell"><header className="topbar"><button className="brand-button" onClick={()=>navigate("Inicio")}><Logo/></button><nav className={`desktop-nav ${mobileOpen?"mobile-open":""}`}>{(["Inicio","Explorar","Mi gato","Agenda"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>navigate(x)}>{x}</button>)}</nav><div className="header-actions"><button className="icon-button" onClick={()=>flash(user?"No tienes alertas nuevas":"Inicia sesión para ver tus alertas")} aria-label="Alertas"><Bell/><span className="dot"/></button>{user?<div className="account-menu"><button className="profile-pill"><span>{user.name.slice(0,2).toUpperCase()}</span><b>{user.name}</b><ChevronDown/></button><div><button onClick={()=>setShowOnboarding(true)}><Sparkles/>Repetir onboarding</button><button onClick={signOut}><LogOut/>Cerrar sesión</button></div></div>:<button className="login-button" onClick={()=>setAuthOpen(true)}>Ingresar</button>}<button className="mobile-menu" onClick={()=>setMobileOpen(!mobileOpen)}>{mobileOpen?<X/>:<Menu/>}</button></div></header>

  <main>{tab==="Inicio"&&<><section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles/> La comunidad felina del Perú</span><h1>Mejores decisiones<br/>para <em>tu gato.</em></h1><p>Descubre productos, servicios y veterinarias recomendadas por personas con gatos como el tuyo.</p><div className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&navigate("Explorar")} placeholder="¿Qué estás buscando para tu gato?"/><button onClick={()=>navigate("Explorar")}>Buscar</button></div><div className="popular"><span>Popular:</span>{["Veterinarias","Arena","Alimento","Hoteles felinos"].map(x=><button key={x} onClick={()=>{setQuery(x);navigate("Explorar")}}>{x}</button>)}</div></div><div className="hero-visual"><div className="cat-photo"/><div className="floating-card score"><span><ShieldCheck/></span><div><b>4.9 de 5</b><small>Opiniones verificadas</small></div></div><div className="floating-card people"><div className="faces"><i>AM</i><i>JR</i><i>LC</i></div><div><b>+12 mil</b><small>cat lovers en Perú</small></div></div></div></section><div className="content-width home-disclaimer"><Disclaimer/></div>
    <section className="quick-section content-width"><div className="section-heading"><div><span className="kicker">EXPLORA MIAUPEDIA</span><h2>Todo lo que tu gato necesita</h2></div><button onClick={()=>navigate("Explorar")}>Ver todo <ChevronRight/></button></div><div className="category-grid">{[["Veterinaria","Especialistas cerca de ti","🏥","lilac"],["Pet Shop","Todo para consentirlo","🛍️","mint"],["Producto","Probados por la comunidad","📦","peach"],["Hotel felino","Un segundo hogar","🏡","blue"],["Cuidador","Personas de confianza","🤝","yellow"]].map(([a,b,c,d])=><button className="category-card" key={a} onClick={()=>{setCategory(a);navigate("Explorar")}}><span className={d}>{c}</span><div><b>{a}</b><small>{b}</small></div><ChevronRight/></button>)}</div></section>
    <section className="recommend-section"><div className="content-width"><div className="section-heading"><div><span className="kicker">RECOMENDADOS PARA TI</span><h2>Los favoritos de la comunidad</h2></div><button onClick={()=>navigate("Explorar")}>Explorar todos <ChevronRight/></button></div><div className="card-grid">{places.slice(0,3).map(p=><PlaceCard key={p.id} place={p} saved={saved.includes(p.id)} onSave={()=>toggleSaved(p.id)} onOpen={()=>setSelected(p)} onCompare={()=>addCompare(p.id)}/>)}</div></div></section>
    <section className="trust-band"><div className="content-width"><div><span className="trust-icon"><ShieldCheck/></span><div><h2>Experiencias reales.<br/>Decisiones con confianza.</h2><p>La comunidad destaca las voces más útiles, no el contenido patrocinado.</p></div></div><div className="trust-stats"><span><b>12K+</b><small>Miembros</small></span><span><b>8.5K</b><small>Reseñas</small></span><span><b>1.2K</b><small>Opciones</small></span></div></div></section></>}

  {tab==="Explorar"&&<section className="page content-width"><div className="page-title"><span className="kicker">DIRECTORIO FELINO</span><h1>Encuentra lo mejor para tu gato</h1><p>Opiniones reales de la comunidad peruana.</p></div><Disclaimer/><div className="explore-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busca por nombre, categoría o distrito"/><button onClick={()=>setShowFilters(!showFilters)}><SlidersHorizontal/>Filtros</button></div>{showFilters&&<div className="filter-panel"><label>Distrito<select value={district} onChange={e=>setDistrict(e.target.value)}><option>Todos</option><option>Miraflores</option><option>Surco</option><option>San Borja</option><option>Barranco</option></select></label><label>Categoría<select value={category} onChange={e=>setCategory(e.target.value)}><option>Todos</option><option>Veterinaria</option><option>Pet Shop</option><option>Hotel felino</option><option>Cuidador</option><option>Producto</option></select></label><label>Ubicación<input disabled value="Lima, Perú"/></label></div>}<div className="chips">{["Todos","Veterinaria","Pet Shop","Producto","Hotel felino","Cuidador"].map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="result-line"><b>{results.length} resultados</b><span>Ordenar: mejor valorados <ChevronDown/></span></div><div className="card-grid explore-grid">{results.map(p=><PlaceCard key={p.id} place={p} saved={saved.includes(p.id)} onSave={()=>toggleSaved(p.id)} onOpen={()=>setSelected(p)} onCompare={()=>addCompare(p.id)}/>)}</div>{!results.length&&<div className="empty"><Search/><h3>No encontramos coincidencias</h3><p>Prueba otra búsqueda o limpia los filtros.</p><button onClick={()=>{setQuery("");setCategory("Todos");setDistrict("Todos")}}>Limpiar filtros</button></div>}{compare.length>0&&<div className="compare-bar"><div><b>{compare.length} producto{compare.length>1?"s":""}</b><small>Seleccionados para comparar</small></div><div className="mini-products">{compare.map(id=><span key={id} style={{backgroundImage:`url(${places.find(p=>p.id===id)?.image})`}}><button onClick={()=>addCompare(id)}><X/></button></span>)}</div><button onClick={()=>setEditor("compare")}>Comparar ahora</button></div>}</section>}

  {tab==="Mi gato"&&<section className="page content-width"><div className="page-title row-title"><div><span className="kicker">MI FAMILIA FELINA</span><h1>Mis gatos</h1><p>Perfiles que personalizan tus descubrimientos.</p></div><button className="primary" onClick={()=>requireUser(()=>{setEditingCat(null);setEditor("cat")})}><Plus/>Añadir gato</button></div>{!user?<LockedState onLogin={()=>setAuthOpen(true)}/>:!cats.length?<div className="empty"><Cat/><h3>Aún no has registrado ningún gato.</h3><p>Añade su perfil para personalizar tu experiencia.</p><button onClick={()=>setEditor("cat")}>Añadir gato</button></div>:<><div className="cat-tabs">{cats.map(c=><button className={c.id===primaryCat.id?"active":""} key={c.id}>{c.name}</button>)}</div><div className="cat-profile"><div className="cat-avatar" style={{backgroundImage:`url(${primaryCat.photo||"https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=700&q=80"})`}}/><div className="cat-info"><div><span>Perfil completo {catCompletion(primaryCat)}%</span><h2>{primaryCat.name}</h2><p>{primaryCat.breed} · {primaryCat.sex} · {primaryCat.age} años</p></div><div className="inline-actions"><button onClick={()=>{setEditingCat(primaryCat);setEditor("cat")}}><Pencil/>Editar</button><button className="danger" onClick={()=>confirm(`¿Eliminar el perfil de ${primaryCat.name}?`)&&setCats(cats.filter(c=>c.id!==primaryCat.id))}><Trash2/></button></div><div className="profile-progress"><i style={{width:`${catCompletion(primaryCat)}%`}}/></div><div className="cat-stats"><span><b>{primaryCat.weight||"—"} kg</b><small>Peso</small></span><span><b>{primaryCat.sterilized?"Sí":"No"}</b><small>Esterilizado</small></span><span><b>{saved.length}</b><small>Seguidos</small></span></div></div></div><Disclaimer/><div className="profile-columns"><div className="panel"><div className="panel-head"><h3>Sus preferencias</h3><button onClick={()=>{setEditingCat(primaryCat);setEditor("cat")}}>Editar</button></div>{[["🍗","Alimentos",primaryCat.food],["✨","Arenas",primaryCat.litter],["🧶","Juguetes",primaryCat.toys]].map(([icon,label,values])=><div className="preference" key={String(label)}><span>{String(icon)}</span><div><small>{String(label)}</small><b>{(values as string[]).join(", ")||"Sin preferencias"}</b></div></div>)}</div><div className="panel"><div className="panel-head"><h3>Otros gatos similares siguen…</h3><button onClick={()=>navigate("Explorar")}>Ver todo</button></div><p className="panel-intro">Basado en raza, edad y esterilización; sin IA.</p>{places.slice(3,5).map(p=><button className="mini-place" key={p.id} onClick={()=>setSelected(p)}><span style={{backgroundImage:`url(${p.image})`}}/><div><small>{p.category}</small><b>{p.name}</b><Stars rating={p.rating}/></div><ChevronRight/></button>)}</div></div></>}</section>}

  {tab==="Agenda"&&<section className="page content-width"><div className="page-title row-title"><div><span className="kicker">CUIDADOS AL DÍA</span><h1>Agenda{primaryCat?` de ${primaryCat.name}`:""}</h1><p>Recordatorios sencillos para que nada se te pase.</p></div><button className="primary" onClick={()=>requireUser(()=>setEditor("reminder"))}><Plus/>Nuevo recordatorio</button></div>{!user?<LockedState onLogin={()=>setAuthOpen(true)}/>:!reminders.length?<div className="empty"><CalendarDays/><h3>No tienes recordatorios todavía</h3><p>Añade cumpleaños, vacunas o desparasitaciones.</p><button onClick={()=>setEditor("reminder")}>Crear recordatorio</button></div>:<div className="agenda-layout"><div className="agenda-main"><h3>Próximos</h3>{[...reminders].sort((a,b)=>a.date.localeCompare(b.date)).map(r=>{const d=new Date(`${r.date}T12:00:00`);return <div className={`event ${r.completed?"completed":""}`} key={r.id}><div className={`date ${r.type==="Vacuna"?"violet":r.type==="Cumpleaños"?"peach":""}`}><b>{String(d.getDate()).padStart(2,"0")}</b><small>{d.toLocaleDateString("es-PE",{month:"short"}).toUpperCase()}</small></div><div><b>{r.description}</b><span>{r.type} · {cats.find(c=>c.id===r.catId)?.name||"Mi gato"}</span></div><button className="event-done" onClick={()=>setReminders(reminders.map(x=>x.id===r.id?{...x,completed:!x.completed}:x))}>{r.completed?"Reabrir":"Completar"}</button><button className="event-delete" onClick={()=>confirm("¿Eliminar este recordatorio?")&&setReminders(reminders.filter(x=>x.id!==r.id))}><Trash2/></button></div>})}</div><aside className="panel calendar-panel"><div className="panel-head"><h3>Resumen</h3><span>{reminders.filter(r=>!r.completed).length} pendientes</span></div><div className="agenda-summary"><CalendarDays/><b>{reminders.filter(r=>!r.completed).length}</b><p>recordatorios activos</p></div></aside></div>}<Disclaimer/></section>}</main>

  <footer><div className="content-width"><Logo/><p>Miaupedia es una plataforma de información y experiencias compartidas por la comunidad. No reemplaza la atención veterinaria profesional ni proporciona diagnósticos, tratamientos o recomendaciones médicas.</p><span>Hecho para los gatos del Perú 🇵🇪</span></div></footer><nav className="bottom-nav">{[["Inicio",Home],["Explorar",Search],["Mi gato",Cat],["Agenda",CalendarDays]].map(([name,Icon])=>{const I=Icon as typeof Home;return <button key={String(name)} className={tab===name?"active":""} onClick={()=>navigate(name as Tab)}><I/><span>{String(name)}</span></button>})}<button onClick={()=>flash("No tienes alertas nuevas")}><Bell/><span>Alertas</span></button></nav>

  {selected&&<DetailModal place={selected} saved={saved.includes(selected.id)} ownReviews={userReviews.filter(r=>r.placeId===selected.id)} onClose={()=>setSelected(null)} onSave={()=>toggleSaved(selected.id)} onContact={()=>requireUser(()=>flash("Conversación privada creada dentro de Miaupedia"))} onNewReview={()=>requireUser(()=>{setEditingReview(null);setEditor("review")})} onEdit={r=>{setEditingReview(r);setEditor("review")}} onDelete={id=>setUserReviews(userReviews.filter(r=>r.id!==id))} onReact={(id,key)=>setUserReviews(userReviews.map(r=>r.id===id?{...r,[key]:r[key]+1}:r))} onReport={id=>setUserReviews(userReviews.map(r=>r.id===id?{...r,reported:true}:r))}/>} 
  {authOpen&&<AuthModal onClose={()=>setAuthOpen(false)} onAuthenticated={u=>{setUser(u);setAuthOpen(false);if(!onboarded)setShowOnboarding(true)}}/>}{showOnboarding&&<Onboarding onSkip={()=>{setOnboarded(true);setShowOnboarding(false)}} onFinish={(cat,interests)=>{if(cat)setCats([cat,...cats.filter(c=>c.id!=="demo-luna")]);setSaved(Array.from(new Set([...saved,...interests])));setOnboarded(true);setShowOnboarding(false);flash("Tu perfil quedó listo")}}/>}
  {editor==="cat"&&<CatEditor initial={editingCat} onClose={()=>setEditor(null)} onSave={cat=>{setCats(editingCat?cats.map(c=>c.id===cat.id?cat:c):[...cats,cat]);setEditor(null);flash("Perfil guardado")}}/>}{editor==="reminder"&&<ReminderEditor cats={cats} onClose={()=>setEditor(null)} onSave={r=>{setReminders([...reminders,r]);setEditor(null);flash("Recordatorio creado")}}/>}{editor==="review"&&selected&&<ReviewEditor initial={editingReview} onClose={()=>setEditor(null)} onSave={r=>{setUserReviews(editingReview?userReviews.map(x=>x.id===r.id?r:x):[...userReviews,{...r,placeId:selected.id}]);setEditor(null);flash("Reseña publicada")}}/>}{editor==="compare"&&<CompareModal ids={compare} onClose={()=>setEditor(null)}/>} {notice&&<div className="toast"><Check/>{notice}</div>}</div>
}

function FormShell({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="form-modal"><button className="close" onClick={onClose}><X/></button><h2>{title}</h2>{children}</div></div>}
function CatEditor({initial,onClose,onSave}:{initial:CatProfile|null;onClose:()=>void;onSave:(c:CatProfile)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);onSave({id:initial?.id||crypto.randomUUID(),name:String(f.get("name")),age:Number(f.get("age")),sex:String(f.get("sex")) as CatProfile["sex"],breed:String(f.get("breed")),sterilized:f.get("sterilized")==="on",birthDate:String(f.get("birthDate")),weight:Number(f.get("weight")),photo:String(f.get("photo")),food:String(f.get("food")).split(",").map(x=>x.trim()).filter(Boolean),litter:String(f.get("litter")).split(",").map(x=>x.trim()).filter(Boolean),toys:String(f.get("toys")).split(",").map(x=>x.trim()).filter(Boolean)})}return <FormShell title={initial?"Editar perfil":"Añadir un gato"} onClose={onClose}><form className="form-grid" onSubmit={submit}><label>Nombre<input name="name" required defaultValue={initial?.name}/></label><label>Edad<input name="age" type="number" min="0" max="30" required defaultValue={initial?.age}/></label><label>Sexo<select name="sex" defaultValue={initial?.sex}><option>Hembra</option><option>Macho</option></select></label><label>Raza<input name="breed" required defaultValue={initial?.breed}/></label><label>Fecha de nacimiento<input name="birthDate" type="date" defaultValue={initial?.birthDate}/></label><label>Peso (kg)<input name="weight" type="number" step="0.1" min="0" defaultValue={initial?.weight}/></label><label className="full-field">URL de foto<input name="photo" type="url" defaultValue={initial?.photo}/></label><label className="full-field">Alimentos favoritos<input name="food" defaultValue={initial?.food.join(", ")} placeholder="Pollo, salmón"/></label><label className="full-field">Arenas favoritas<input name="litter" defaultValue={initial?.litter.join(", ")}/></label><label className="full-field">Juguetes favoritos<input name="toys" defaultValue={initial?.toys.join(", ")}/></label><label className="check-label full-field"><input name="sterilized" type="checkbox" defaultChecked={initial?.sterilized}/> Esterilizado</label><button className="primary full-field">Guardar perfil</button></form></FormShell>}
function ReminderEditor({cats,onClose,onSave}:{cats:CatProfile[];onClose:()=>void;onSave:(r:Reminder)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);onSave({id:crypto.randomUUID(),catId:String(f.get("catId")),type:String(f.get("type")) as Reminder["type"],date:String(f.get("date")),description:String(f.get("description")),completed:false})}return <FormShell title="Nuevo recordatorio" onClose={onClose}><form className="stack-form" onSubmit={submit}><label>Gato<select name="catId" required>{cats.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Tipo<select name="type"><option>Cumpleaños</option><option>Vacuna</option><option>Desparasitación</option></select></label><label>Fecha<input name="date" type="date" required/></label><label>Descripción<input name="description" required placeholder="Ej. Vacuna anual"/></label><button className="primary full">Crear recordatorio</button></form></FormShell>}
function ReviewEditor({initial,onClose,onSave}:{initial:UserReview|null;onClose:()=>void;onSave:(r:UserReview)=>void}){const [error,setError]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),comment=String(f.get("comment")),problem=validateCommunityContent(comment);if(problem){setError(problem);return}onSave({id:initial?.id||crypto.randomUUID(),placeId:initial?.placeId||0,rating:Number(f.get("rating")),comment,status:initial?.status||"Nueva",createdAt:initial?.createdAt||new Date().toISOString(),helpful:initial?.helpful||0,unhelpful:initial?.unhelpful||0,reported:false})}return <FormShell title={initial?"Editar reseña":"Comparte tu experiencia"} onClose={onClose}><Disclaimer/><form className="stack-form" onSubmit={submit}><label>Calificación<select name="rating" defaultValue={initial?.rating||5}><option value="5">5 · Excelente</option><option value="4">4 · Muy buena</option><option value="3">3 · Buena</option><option value="2">2 · Regular</option><option value="1">1 · Mala</option></select></label><label>Comentario<textarea name="comment" required defaultValue={initial?.comment} placeholder="Describe tu experiencia sin incluir recomendaciones médicas."/></label>{error&&<p className="form-error">{error}</p>}<button className="primary full">Publicar reseña</button></form></FormShell>}
function CompareModal({ids,onClose}:{ids:number[];onClose:()=>void}){return <FormShell title="Comparador de productos" onClose={onClose}><div className="comparison-table"><div><b>Producto</b><b>Precio</b><b>Puntuación</b><b>Reseñas</b></div>{ids.map(id=>{const p=places.find(x=>x.id===id)!;return <div key={id}><strong>{p.name}</strong><span>{p.price}</span><Stars rating={p.rating}/><span>{p.reviews}</span></div>})}</div></FormShell>}
function DetailModal({place,saved,ownReviews,onClose,onSave,onContact,onNewReview,onEdit,onDelete,onReact,onReport}:{place:Place;saved:boolean;ownReviews:UserReview[];onClose:()=>void;onSave:()=>void;onContact:()=>void;onNewReview:()=>void;onEdit:(r:UserReview)=>void;onDelete:(id:string)=>void;onReact:(id:string,key:"helpful"|"unhelpful")=>void;onReport:(id:string)=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="detail-modal"><button className="close" onClick={onClose}><X/></button><div className="detail-photo" style={{backgroundImage:`url(${place.image})`}}/><div className="detail-body"><span className="kicker">{place.category} · {place.district}</span><h2>{place.name}</h2><div className="detail-rating"><Stars rating={place.rating}/><span>{place.reviews+ownReviews.length} reseñas</span>{place.open&&<span className="open">Abierto ahora</span>}</div><p>Información de la ficha: dirección en {place.district}, atención y horarios sujetos a confirmación con el negocio.</p>{place.category==="Veterinaria"&&<div className="service-icons">{["24 horas","Hospitalización","Laboratorio","Ecografía","Cirugía","Atención felina"].map(x=><span key={x}><Check/>{x}</span>)}</div>}<div className="detail-actions"><button className="primary" onClick={onSave}><Bookmark/>{saved?"Siguiendo":"Seguir"}</button><button onClick={onContact}><MessageCircle/>Contacto privado</button></div><Disclaimer/><div className="review-title"><h3>Lo que dice la comunidad</h3><button onClick={onNewReview}>Escribir reseña</button></div>{ownReviews.map(r=><div className="review own" key={r.id}><span className="review-avatar">TÚ</span><div><div className="review-head"><b>Tu reseña · {r.status}</b><Stars rating={r.rating}/></div><small>{new Date(r.createdAt).toLocaleDateString("es-PE")} · Nivel Activo</small><p>{r.comment}</p><div className="review-actions"><button onClick={()=>onReact(r.id,"helpful")}>Útil ({r.helpful})</button><button onClick={()=>onReact(r.id,"unhelpful")}>No útil ({r.unhelpful})</button><button onClick={()=>onReport(r.id)} disabled={r.reported}>{r.reported?"Reportada":"Reportar"}</button><button onClick={()=>onEdit(r)}>Editar</button><button onClick={()=>confirm("¿Eliminar esta reseña?")&&onDelete(r.id)}>Eliminar</button></div></div></div>)}{reviews.map(r=><div className="review" key={r.user}><span className="review-avatar">{r.avatar}</span><div><div className="review-head"><b>{r.user}</b><Stars rating={r.rating}/></div><small>{r.cat} · Nivel {r.level}</small><p>{r.text}</p><span>{r.date} · Útil ({r.helpful})</span></div></div>)}</div></div></div>}
